name: CI/CD
on:
  pull_request:
    branches:
      - main

jobs:
  lint-format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install Dependencies
        run: pnpm install

      - name: Code Quality and Security Checks
        run: |
          pnpm run lint:biome
          pnpm run check:biome
          pnpm run format:biome

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm run build

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm run test:ci